"""add prd field parity to fare_observations

Revision ID: 0173c67f0814
Revises: 6be333838c34
Create Date: 2026-09-02 10:27:38.308805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0173c67f0814'
down_revision: Union[str, None] = '6be333838c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_observations', sa.Column('travel_date', sa.Date(), nullable=True))
    op.add_column('fare_observations', sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('fare_observations', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('fare_observations', sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('fare_observations', sa.Column('availability', sa.SmallInteger(), nullable=True))
    op.add_column('fare_observations', sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('fare_observations', 'source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_fare_observations_travel_date'), 'fare_observations', ['travel_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fare_observations_travel_date'), table_name='fare_observations')
    op.alter_column('fare_observations', 'source',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('fare_observations', 'collected_at')
    op.drop_column('fare_observations', 'availability')
    op.drop_column('fare_observations', 'fees')
    op.drop_column('fare_observations', 'tax')
    op.drop_column('fare_observations', 'base_fare')
    op.drop_column('fare_observations', 'travel_date')
    # ### end Alembic commands ###
