"""initial schema

Revision ID: 6be333838c34
Revises: 
Create Date: 2026-08-31 23:56:29.492054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be333838c34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlines_iata_code'), 'airlines', ['iata_code'], unique=True)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=True)
    op.create_index(op.f('ix_airports_region'), 'airports', ['region'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'IDLE', 'FAILED', name='source_status_enum'), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'WARNING', 'FAILED', name='job_status_enum'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=False),
    sa.Column('invalid_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('missing_value_records', sa.Integer(), nullable=False),
    sa.Column('rejected_records', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_airport_id', sa.Integer(), nullable=False),
    sa.Column('destination_airport_id', sa.Integer(), nullable=False),
    sa.Column('display_code', sa.String(length=10), nullable=False),
    sa.Column('index_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_airport_id', 'destination_airport_id', name='uq_route_pair')
    )
    op.create_index(op.f('ix_routes_destination_airport_id'), 'routes', ['destination_airport_id'], unique=False)
    op.create_index(op.f('ix_routes_display_code'), 'routes', ['display_code'], unique=False)
    op.create_index(op.f('ix_routes_origin_airport_id'), 'routes', ['origin_airport_id'], unique=False)
    op.create_table('fare_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('travel_class', sa.Enum('ECONOMY', 'BUSINESS', 'FIRST', name='travel_class_enum'), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('days_to_departure', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fare_observations_airline_id'), 'fare_observations', ['airline_id'], unique=False)
    op.create_index(op.f('ix_fare_observations_days_to_departure'), 'fare_observations', ['days_to_departure'], unique=False)
    op.create_index(op.f('ix_fare_observations_dedup_hash'), 'fare_observations', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_fare_observations_ingestion_job_id'), 'fare_observations', ['ingestion_job_id'], unique=False)
    op.create_index(op.f('ix_fare_observations_observation_date'), 'fare_observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_fare_observations_route_id'), 'fare_observations', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fare_observations_route_id'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_observation_date'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_ingestion_job_id'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_dedup_hash'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_days_to_departure'), table_name='fare_observations')
    op.drop_index(op.f('ix_fare_observations_airline_id'), table_name='fare_observations')
    op.drop_table('fare_observations')
    op.drop_index(op.f('ix_routes_origin_airport_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_display_code'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination_airport_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('ingestion_jobs')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_airports_region'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_iata_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
