"""add collection_runs, route_priorities, index_values

Revision ID: 884f8c767d86
Revises: 0173c67f0814
Create Date: 2026-09-04 09:44:43.117607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884f8c767d86'
down_revision: Union[str, None] = '0173c67f0814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='collection_run_status_enum'), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('routes_attempted', sa.Integer(), nullable=False),
    sa.Column('routes_successful', sa.Integer(), nullable=False),
    sa.Column('routes_failed', sa.Integer(), nullable=False),
    sa.Column('observations_found', sa.Integer(), nullable=False),
    sa.Column('observations_saved', sa.Integer(), nullable=False),
    sa.Column('observations_rejected', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('base_period', sa.Date(), nullable=False),
    sa.Column('index_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sample_size', sa.SmallInteger(), nullable=False),
    sa.Column('methodology_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_values_period'), 'index_values', ['period'], unique=False)
    op.create_index(op.f('ix_index_values_scope'), 'index_values', ['scope'], unique=False)
    op.create_table('route_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('historical_frequency_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('live_availability_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('airline_count_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_demo_priority', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_priorities_route_code'), 'route_priorities', ['route_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_priorities_route_code'), table_name='route_priorities')
    op.drop_table('route_priorities')
    op.drop_index(op.f('ix_index_values_scope'), table_name='index_values')
    op.drop_index(op.f('ix_index_values_period'), table_name='index_values')
    op.drop_table('index_values')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
