"""make ingestion_job_id nullable, add collection_run_id to fare_observations

Revision ID: e126ac6b98e2
Revises: 884f8c767d86
Create Date: 2026-09-04 09:46:11.869368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e126ac6b98e2'
down_revision: Union[str, None] = '884f8c767d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_observations', sa.Column('collection_run_id', sa.Integer(), nullable=True))
    op.alter_column('fare_observations', 'ingestion_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_fare_observations_collection_run_id'), 'fare_observations', ['collection_run_id'], unique=False)
    op.create_foreign_key(None, 'fare_observations', 'collection_runs', ['collection_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fare_observations', type_='foreignkey')
    op.drop_index(op.f('ix_fare_observations_collection_run_id'), table_name='fare_observations')
    op.alter_column('fare_observations', 'ingestion_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('fare_observations', 'collection_run_id')
    # ### end Alembic commands ###
